@echo off
echo _______________________________________________________________________________
echo [                                                                             ]
echo [                          Coding Paper tutorial                              ]
echo [                     The tutorial for coding on paper.                       ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [          Coding Paper was created on 30th October 2014 to give you          ]
echo [          advice on how to code on paper, which was first adopted by         ]
echo [               Systegear which created this tutorial in return.              ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                       Brought To You By Systegear                           ]
echo [                            For Coding Paper                                 ]
echo _______________________________________________________________________________
timeout 5 /nobreak
pause
cls
echo _______________________________________________________________________________
echo [                                                                             ]
echo [                          Coding Paper tutorial                              ]
echo [                     The tutorial for coding on paper.                       ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [        This tutorial will indicate your Requirements and How To Start       ]
echo [        Coding on a paper. This is a tutorial in only 8 steps. This i-       ]
echo [             s an official tutorial coming from Coding Paper.                ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                       Brought To You By Systegear                           ]
echo [                            For Coding Paper                                 ]
echo _______________________________________________________________________________
pause
cls
echo _______________________________________________________________________________
echo [                                                                             ]
echo [                          Coding Paper tutorial                              ]
echo [                     The tutorial for coding on paper.                       ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                             REQUIREMENTS-:                                  ]
echo [                                                                             ]
echo [                               1. Paper                                      ]
echo [                              2. Blue Pen                                    ]
echo [                 3. Black Pen(if your paper has no lines)                    ]
echo [                              3. Red Pen                                     ]
echo [                   4. Ruler (if your paper has no lines)                     ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                       Brought To You By Systegear                           ]
echo [                            For Coding Paper                                 ]
echo _______________________________________________________________________________
pause
cls
echo _______________________________________________________________________________
echo [                                                                             ]
echo [                          Coding Paper tutorial                              ]
echo [                     The tutorial for coding on paper.                       ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                  STEPS-:                                    ]
echo [                                                                             ]
echo [                          1. Get your pens ready.                            ]
echo [                         2. Get your paper ready.                            ]
echo [        3. On the first page write Coding Paper then in a list write t-      ]
echo [         he code/program name then the coding/programming language you       ]
echo [        are using then write the developer name (yours) then the date        ]
echo [                  of creation then the copyright.                            ]
echo [        4. On the second page make a rough code or mind map to help you      ]
echo [                                   out                                       ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                       Brought To You By Systegear                           ]
echo [                            For Coding Paper                                 ]
echo _______________________________________________________________________________
pause
cls
echo _______________________________________________________________________________
echo [                                                                             ]
echo [                          Coding Paper tutorial                              ]
echo [                     The tutorial for coding on paper.                       ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                  STEPS-:                                    ]
echo [                                                                             ]
echo [       5. On the third page make lines with a black pen and a ruler, if      ]
echo [                   you do have lines no need to redraw them.                 ]
echo [                            6. Start coding!                                 ]
echo [       7. Check your errors and underline it in red and make a small r-      ]
echo [       ed triangle to mark your errors or just make a small red triang-      ]
echo [                          le if it is incorrect.                             ]
echo [                              8. Have Fun!                                   ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                                                                             ]
echo [                       Brought To You By Systegear                           ]
echo [                            For Coding Paper                                 ]
echo _______________________________________________________________________________
pause
cls
echo _______________________________________________________________________________
echo [                                                                             ]
echo [                          Coding Paper tutorial                              ]
echo [                     The tutorial for coding on paper.                       ]
echo [                                                                             ]
echo [                              CREDITS-:                                      ]
echo [             Thank you if you have watched this offline tutorial             ]
echo [                                                                             ]
echo [           This tutorial was made by Systegear for Coding Paper.             ]
echo [                                                                             ]
echo [                    Coding Paper's Official Website-:                        ]
echo [                            codingpaper.cu.cc                                ]
echo [                                                                             ]
echo [                      Systegear's official Website-:                         ]
echo [                             systegear.cu.cc                                 ]
echo [                                                                             ]
echo [                                                                             ]
echo [                       Coding Paper Copyright 2014                           ]
echo [                         Systegear Copyright 2014                            ]
echo [                                                                             ]
echo [                       Brought To You By Systegear                           ]
echo [                            For Coding Paper                                 ]
echo _______________________________________________________________________________
pause
